### ISSUE TITLE
support contextBridge api

### ISSUE THREAD

**Issue by musou1500** [klarna/electron-redux#235] opened 2020-08-03 13:26 UTC
**Is your feature request related to a problem? Please describe.**

we need to use preload script or `nodeIntegration` option to use `electron-redux`.
I think preload script is ideal for security perspective.
I often load application hosted on local server while developing(I believe it is common usecase).
but application can not be loaded as preload script in this way.
It requires us to additional branch.

**Describe the solution you'd like**

I propose to support `contextBridge` api.
I am assuming expose simple api that communicate with main process using `ipcRenderer` api through contextBridge.
in this way, application on renderer process can use `electron-redux` regardless it is loaded through local server or preload script.

**Comment by Slapbox** [comment] 2020-12-07 20:24
This is really crucial for security. @matmalkowski are there any plans for this?

**Comment by matmalkowski** [comment] 2020-12-07 20:34
@musou1500 @Slapbox I think we could support contextBridge in v2, since right now communication is all done with ipc (`ipcRenderer` & `ipcMain` only)

**Comment by Slapbox** [comment] 2021-02-04 19:38
@matmalkowski any update on a timeline for v2? Do you think this might be addressed once v2 is out? We're really looking forward to its release!

**Comment by matmalkowski** [comment] 2021-02-05 12:48
Yeah, I actually got an issue already created for that: #289 , just slightly different naming. Right now I'm quite busy with other stuff, so it is hard to tell when this could be incorporated into v2, but the general plan is to include that in the version 2, finish up the documentation and create a stable release afterwards. If you are interested, you may take a look at the issue, it links to possible implementation in the fork of that project, and raise a PR to v2 if you have some spare time to implement it

**Comment by matmalkowski** [comment] 2021-02-09 20:32
Closing as duplicate of #289, we can continue all discussions in that ticket 👍🏻

**Closed by matmalkowski** 2021-02-09 20:32 UTC
Labels: duplicate, feature idea, v2
